name: colmap
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - colmap
  - jupyter
  - matplotlib
  - opencv
  - python=3.9.15
  - pip=22.3.1
  - pip:
    - imageio
    - scikit-image
    - scipy
